blog/urls.py
from django.contrib import admin
from django.urls import path
from posts import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('collections/', views.category, name = "categories"),
    path('collections/<str:slug>/', views.products, name = "products"),
    path('collections/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name = "product_detail"),


    # Регистрация страница новая
    path('registr.html', views.registr_view, name="registr"),
    path('login/', views.login_view, name='login'),


] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove_cart'),
]

wokiee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # debug-toolbar
    path('__debug__/', include('debug_toolbar.urls')),

    # user-management
    path('accounts/', include('django.contrib.auth.urls')),

    # local
    path('', include('dishes.urls')),
    path('users/', include('users.urls')),
    path('', include(('cart.urls', 'cart_detail'), namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

cart/models.py
from django.db import models

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
            choices=PRODUCT_QUANTITY_CHOICES,
            coerce=int,
        )
    update = forms.BooleanField(
            required=False,
            initial=False,
            widget=forms.HiddenInput()
        )

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from dishes.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = \
            CartAddProductForm(initial={'quantity': item['quantity'],
                                        'update': True})
    return render(request, 'cart/cart_detail.html', {'cart': cart})

templates/cart/cart_detail.html
{% extends "_base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
    <div class="container cart-table">
    <h1>Shopping cart</h1>
    <table class="cart" style="margin-top: 200px;">
        <tbody>
            {% for item in cart %}
            {% with product=item.product %}
            <tr style="border-top: 1px solid #393939; border-bottom: 1px solid #393939;">
                <td>
                    <a href="{{ product.get_absolute_url }}">
                    <img src="{{ product.image.url }}">
                    </a>
                </td>
                <td class="product-title">{{ product.category }} "{{ product.title }}"</td>
                <td>
                    <form action="{% url 'cart:add_cart' product.id %}" method="post">
                        <span class="quantity">{{ item.update_quantity_form.quantity }}</span>
                        {{ item.update_quantity_form.update }}
                        <input type="submit" value="Update">
                        {% csrf_token %}
                    </form>
                </td>
                <td class="price">${{ item.price }}</td>
                <td class="total_price">${{ item.total_price }}</td>
                <td>
                    <a href="{% url 'cart:remove_cart' product.id %}">
                    <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr>
            {% endwith %}
            {% endfor %}
        </tbody>
    </table>
    <h3>Total: <span>${{ cart.get_total_price }}</span></h3>
    <button>Buy</button>
</div>
{% endblock %}