blog/urls.py
from django.contrib import admin
from django.urls import path
from posts import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"),
    path('collections/', views.category, name = "categories"),
    path('collections/<str:slug>/', views.products, name = "products"),
    path('collections/<slug:category_slug>/<slug:product_slug>/', views.product_detail, name = "product_detail"),


    # Регистрация страница новая
    path('registr.html', views.registr_view, name="registr"),
    path('login/', views.login_view, name='login'),


] + static(settings.STATIC_URL, document_root = settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='add_cart'),
    path('remove/<int:product_id>/', views.cart_remove, name='remove_cart'),
]

wokiee/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # admin
    path('admin/', admin.site.urls),

    # debug-toolbar
    path('__debug__/', include('debug_toolbar.urls')),

    # user-management
    path('accounts/', include('django.contrib.auth.urls')),

    # local
    path('', include('dishes.urls')),
    path('users/', include('users.urls')),
    path('', include(('cart.urls', 'cart_detail'), namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Food Delivery</title>
        <!-- ICONS -->
        <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon.ico' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
        <!-- STYLES -->
        <!-- GENERAL STYLES -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
        <!-- APP STYLES -->
        <link rel="stylesheet" href="{% static 'dishes/css/dishes.css' %}">
        <link rel="stylesheet" href="{% static 'users/css/accounts.css' %}">
        <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
        <!-- FONTS -->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Luckiest+Guy&display=swap" rel="stylesheet">
    </head>
    <body>
        <div class="wrapper">
            <header class="fixed-top" style="background: rgb(14, 14, 14);">
                <div class="hamburger">
                    <input type="checkbox" id="hmt" class="hidden-menu-ticker">
                    <label for="hmt" class="btn-menu">
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                    </label>
                    <hr>
                    <ul class="hidden-menu">
                        <li class="mt-5"><a href="{% url 'categories' %}">our menu</a></li>
                        <li class=""><a href="">about us</a></li>
                        <li class=""><a href="">shipping area</a></li>
                    </ul>
                </div>
                <a href="{% url 'index' %}"><img class="logo" src="{% static 'dishes/img/logo.webp' %}" alt=""></a>
                <nav>
                    <ul class="nav__links">
                        <li class="nav__item">
                            <div class="dropdown">
                                <a href="{% url 'categories' %}" class="dropbtn">our menu</a>
                                <div class="dropdown-content">
                                    {% for category in categories %}
                                    <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                                    {% endfor %}
                                </div>
                            </div>
                        </li>
                        <li class="nav__item"><a class="nav__link" href="">about us</a></li>
                        <li class="nav__item"><a class="nav__link" href="">shipping area</a></li>
                    </ul>
                </nav>
                <div class="icons d-flex">
                    <a href="{% url 'cart:cart_detail' %}" class="cart"><i class="bi bi-basket3"></i></a>
                    <div class="dropdown rounded-0">
                        <a class="dropdown" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="bi bi-person"></i>
                        </a>
                        {% if user.is_authenticated %}
                        <ul class="dropdown-menu auth-menu rounded-0" aria-labelledby="dropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{% url 'profile' %}">
                                <i class="bi bi-person"></i>
                                Account
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'logout' %}">
                                <i class="bi bi-lock"></i>
                                Log Out
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                <i class="bi bi-basket3"></i>
                                View cart
                                </a>
                            </li>
                        </ul>
                        {% else %}
                        <ul class="dropdown-menu auth-menu rounded-0" aria-labelledby="dropdownMenuLink">
                            <li>
                                <a class="dropdown-item" href="{% url 'login' %}">
                                <i class="bi bi-lock"></i>
                                Sign in
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'signup' %}">
                                <i class="bi bi-person"></i>
                                Register
                                </a>
                            </li>
                            <li>
                                <a class="dropdown-item" href="#">
                                <i class="bi bi-basket3"></i>
                                View cart
                                </a>
                            </li>
                        </ul>
                        {% endif %}
                    </div>
                </div>
            </header>
            <a class="logo2" href="{% url 'index' %}"><img src="{% static 'dishes/img/logo.webp' %}" alt=""></a>
            <main>
                {% block content %}
                {% endblock content %}
            </main>
        </div>
        <div class="footer">
            <footer>
                <div class="row justify-content-between py-5 ">
                    <div class="col-lg-3 col-2 col-sm-6 col-md-6 mt-4">
                        <h5>cull us</h5>
                        <ul class="nav flex-column">
                            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">(267) 730-8765</a></li>
                            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">(267) 730-8754</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3 col-2 col-sm-6 col-md-6 mt-4">
                        <h5>hours</h5>
                        <ul class="nav flex-column">
                            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">T-F: 7AM – 5PM</a></li>
                            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">S-SU: 8AM – 5PM</a></li>
                        </ul>
                    </div>
                    <div class="col-lg-3 col-2 col-sm-6 col-md-6 mt-4">
                        <h5>location</h5>
                        <ul class="nav flex-column">
                            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">242 S 11th St.</a></li>
                            <li class="nav-item mb-2"><a href="#" class="nav-link p-0 text-muted">Philly, NYC 19107</a></li>
                        </ul>
                    </div>
                    <div class="col-4 col-md-6 mt-4">
                        <form>
                            <h5>NEWSLETTER SIGNUP</h5>
                            <p>Sign up for our e-mail and be the first who know our special offers!</p>
                            <div class="d-flex w-100 gap-2">
                                <label for="newsletter1" class="visually-hidden">Email address</label>
                                <input id="newsletter1" type="text" class="form-control rounded-0" placeholder="Enter your e-mail">
                                <button class="btn btn-primary rounded-0" type="button">JOIN US</button>
                            </div>
                        </form>
                        <ul class="nav icons">
                            <li class="nav-item mb-2"><i class="bi bi-facebook"></i></li>
                            <li class="nav-item mb-2"><i class="bi bi-twitter"></i></li>
                            <li class="nav-item mb-2"><i class="bi bi-google"></i></li>
                            <li class="nav-item mb-2"><i class="bi bi-instagram"></i></li>
                            <li class="nav-item mb-2"><i class="bi bi-pinterest"></i></li>
                        </ul>
                    </div>
                </div>
                <div class="d-flex mb-5" style="position: relative; bottom: 50px;">
                    <img src="{% static 'dishes/img/logo.webp' %}" alt="">
                    <p style="position: relative; top: 10px; left: 10px">© Wokiee 2022. All Rights Reserved</p>
                </div>
            </footer>
        </div>
        <div class="footer2">
            <footer>
                <section class="d-flex section-1 justify-content-beetween">
                    <h5 class="col">call us</h5>
                    <button onclick="myFunction1()" class="">╋</button>
                </section>
                <div class="hide-content" id="hide-content-1" style="display: none;">
                    <h4>(267) 730-8765</h4>
                    <h4>(267) 730-8754</h4>
                </div>
                <section class="d-flex section-1 justify-content-beetween">
                    <h5 class="col">hours</h5>
                    <button onclick="myFunction2()" class="">╋</button>
                </section>
                <div class="hide-content" id="hide-content-2" style="display: none;">
                    <h4>T-F: 7AM – 5PM</h4>
                    <h4>S-SU: 8AM – 5PM</h4>
                </div>
                <section class="d-flex section-1 justify-content-beetween">
                    <h5 class="col">location</h5>
                    <button onclick="myFunction3()" class="">╋</button>
                </section>
                <div class="hide-content" id="hide-content-3" style="display: none;">
                    <h4>242 S 11th St.</h4>
                    <h4>Philly, NYC 19107</h4>
                </div>
                <section class="d-flex section-1 justify-content-beetween">
                    <h5 class="col">newsletter signup</h5>
                    <button onclick="myFunction4()" class="">╋</button>
                </section>
                <div class="hide-content" id="hide-content-4" style="display: none;">
                    <form>
                        <p>Sign up for our e-mail and be the first who know our special offers!</p>
                        <div class="d-block w-100 gap-2">
                            <label for="newsletter1" class="visually-hidden">Email address</label>
                            <input id="newsletter1" type="text" class="form-control rounded-0" placeholder="Enter your e-mail">
                            <button class="btn btn-primary rounded-0" type="button">JOIN US</button>
                        </div>
                    </form>
                </div>
                <div class="col-4">
                    <ul class="nav">
                        <li class="nav-item mb-2"><i style="font-size: 15px;" class="bi bi-facebook"></i></li>
                        <li class="nav-item mb-2"><i style="font-size: 15px;" class="bi bi-twitter"></i></li>
                        <li class="nav-item mb-2"><i style="font-size: 15px;" class="bi bi-google"></i></li>
                        <li class="nav-item mb-2"><i style="font-size: 15px;" class="bi bi-instagram"></i></li>
                        <li class="nav-item mb-2"><i style="font-size: 15px;" class="bi bi-pinterest"></i></li>
                    </ul>
                </div>
                <div class="text-center mb-5 mt-5" style="position: relative; bottom: 50px; text-transform: none;">
                    <img src="{% static 'dishes/img/logo.webp' %}" alt="">
                    <p style="font-family: 'Roboto', sans-serif; color: #fff; margin-top: 5px;">© Wokiee 2022. All Rights Reserved</p>
                </div>
            </footer>
        </div>

		<script>
			function myFunction1() {
			  var x = document.getElementById("hide-content-1");
			  if (x.style.display === "none") {
				x.style.display = "block";
			  } else {
				x.style.display = "none";
			  }
			}
		</script>

		<script>
			function myFunction2() {
			  var x = document.getElementById("hide-content-2");
			  if (x.style.display === "none") {
				x.style.display = "block";
			  } else {
				x.style.display = "none";
			  }
			}
		</script>

		<script>
			function myFunction3() {
			  var x = document.getElementById("hide-content-3");
			  if (x.style.display === "none") {
				x.style.display = "block";
			  } else {
				x.style.display = "none";
			  }
			}
		</script>

		<script>
			function myFunction4() {
			  var x = document.getElementById("hide-content-4");
			  if (x.style.display === "none") {
				x.style.display = "block";
			  } else {
				x.style.display = "none";
			  }
			}
		</script>



		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/custom.js' %}"></script>
	</body>
		
</html>